---
title: "About"
---

I am an Economics student at St. Olaf College in Northfield, Minnesota. My research interests include european integration and development in post-Soviet states. Last spring, I wrote a paper on whether countries that joined the European Union experienced social convergence in the aftermath. This fall, I am working on a paper that explores the relationship between rising temperatures and exports from Brazil. My final project for Data Science 1 synthesized 36 data tables from the NSF on graduate school participation by sex, parent education, and citizenship. I employed R to illustrate changes in the graduate school landscape and promote greater access to mentorship for undergraduates considering careers in academia. For my first mini project in Data Science 2, I created static and choropleth maps for data on obesity rates by state and bikeshare systems in cities. Later, I acquired and cleaned data from the Penguin Random House Events page to format and house data on book events.